# Generated by Django 4.1.3 on 2022-11-17 06:28

from django.db import migrations
import paper_jsoneditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='ordered_json',
            field=paper_jsoneditor.fields.OrderedJSONField(default=dict, verbose_name='JSON (order preserved)'),
        ),
    ]
