# Generated by Django 4.1.3 on 2022-11-16 15:22

from django.db import migrations
import paper_jsoneditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='data',
            field=paper_jsoneditor.fields.OrderedJSONField(blank=True, default=dict, verbose_name='JSON (order preserved)'),
        ),
    ]
