# Generated by Django 4.1.3 on 2022-11-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sample_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='data',
            new_name='ordered_data',
        ),
    ]
